name: alitapricelist
description: "Alita Price List"

publish_to: 'none'

version: 1.7.41+69
environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.6.1
  
  # Navigation
  go_router: ^14.6.2
  app_links: ^6.3.2
  
  # UI & Styling 
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  
  # Data Classes
  freezed_annotation: ^2.4.4
  
  # Storage
  shared_preferences: ^2.3.3
  
  # External Links
  url_launcher: ^6.3.1
  
  # Networking
  http: ^1.2.2
  
  # Environment Config
  flutter_dotenv: ^5.2.1

  # Formatting
  intl: ^0.20.2
  
  # Image Caching
  cached_network_image: ^3.4.1

  # Connectivity
  connectivity_plus: ^6.1.1

  # Icons
  image_picker: ^1.2.1
  geolocator: ^13.0.2
  geocoding: ^3.0.0

  # PDF Generation & Sharing
  pdf: ^3.11.3
  printing: ^5.13.3
  share_plus: ^10.1.4
  path_provider: ^2.1.5

  # Firebase
  firebase_core: ^4.6.0
  firebase_analytics: ^12.2.0
  firebase_crashlytics: ^5.1.0
  cloud_functions: ^6.1.0
  firebase_messaging: ^16.1.3
  flutter_local_notifications: ^18.0.1
  firebase_auth: ^6.3.0
  firebase_data_connect: ^0.2.4
  upgrader: ^12.5.0
  package_info_plus: ^8.0.0
  flutter_secure_storage:
    path: packages/flutter_secure_storage
  in_app_update: ^4.2.5
  firebase_app_check: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  # Mocking
  mocktail: ^1.0.4

  # Linting
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logo/
    - .env
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
        - asset: assets/fonts/Inter-Italic-VariableFont_opsz,wght.ttf
          style: italic
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter_18pt-Bold.ttf
          weight: 700
