// Mocks generated by Mockito 5.4.6 from annotations
// in alitapricelist/test/features/approval/data/repositories/approval_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:alitapricelist/services/order_letter_service.dart' as _i3;
import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [OrderLetterService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderLetterService extends _i1.Mock
    implements _i3.OrderLetterService {
  MockOrderLetterService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_0(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i2.Dio);

  @override
  _i4.Future<Map<String, dynamic>> createOrderLetterWithDetails({
    required Map<String, dynamic>? orderLetterData,
    required List<Map<String, dynamic>>? detailsData,
    required dynamic discountsData,
    List<int?>? leaderIds,
    int? selectedSpvId,
    String? selectedSpvName,
    int? selectedRsmId,
    String? selectedRsmName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createOrderLetterWithDetails,
          [],
          {
            #orderLetterData: orderLetterData,
            #detailsData: detailsData,
            #discountsData: discountsData,
            #leaderIds: leaderIds,
            #selectedSpvId: selectedSpvId,
            #selectedSpvName: selectedSpvName,
            #selectedRsmId: selectedRsmId,
            #selectedRsmName: selectedRsmName,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> createOrderLetter(
          Map<String, dynamic>? orderLetterData) =>
      (super.noSuchMethod(
        Invocation.method(
          #createOrderLetter,
          [orderLetterData],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> createOrderLetterDetail(
          Map<String, dynamic>? detailData) =>
      (super.noSuchMethod(
        Invocation.method(
          #createOrderLetterDetail,
          [detailData],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> createOrderLetterDiscount(
          Map<String, dynamic>? discountData) =>
      (super.noSuchMethod(
        Invocation.method(
          #createOrderLetterDiscount,
          [discountData],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> batchApproveOrderLetterDiscounts({
    required int? orderLetterId,
    required int? leaderId,
    required int? jobLevelId,
    String? action = 'approve',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchApproveOrderLetterDiscounts,
          [],
          {
            #orderLetterId: orderLetterId,
            #leaderId: leaderId,
            #jobLevelId: jobLevelId,
            #action: action,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> approveOrderLetterDiscount({
    required int? discountId,
    required int? leaderId,
    required int? jobLevelId,
    required int? orderLetterId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #approveOrderLetterDiscount,
          [],
          {
            #discountId: discountId,
            #leaderId: leaderId,
            #jobLevelId: jobLevelId,
            #orderLetterId: orderLetterId,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getOrderLetters({
    String? creator,
    String? dateFrom,
    String? dateTo,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrderLetters,
          [],
          {
            #creator: creator,
            #dateFrom: dateFrom,
            #dateTo: dateTo,
          },
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getOrderLettersWithCompleteData({
    String? creator,
    bool? includeDetails = true,
    bool? includeDiscounts = true,
    bool? includeApprovals = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrderLettersWithCompleteData,
          [],
          {
            #creator: creator,
            #includeDetails: includeDetails,
            #includeDiscounts: includeDiscounts,
            #includeApprovals: includeApprovals,
          },
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getOrderLetterDetails(
          {int? orderLetterId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrderLetterDetails,
          [],
          {#orderLetterId: orderLetterId},
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getOrderLetterDiscounts(
          {int? orderLetterId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrderLetterDiscounts,
          [],
          {#orderLetterId: orderLetterId},
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getOrderLetterApproves({
    int? orderLetterId,
    String? approverId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrderLetterApproves,
          [],
          {
            #orderLetterId: orderLetterId,
            #approverId: approverId,
          },
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<Map<String, dynamic>> createOrderLetterApprove(
          Map<String, dynamic>? approveData) =>
      (super.noSuchMethod(
        Invocation.method(
          #createOrderLetterApprove,
          [approveData],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<int> getPendingDiscountCount({
    required int? orderLetterId,
    required int? leaderId,
    required int? jobLevelId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingDiscountCount,
          [],
          {
            #orderLetterId: orderLetterId,
            #leaderId: leaderId,
            #jobLevelId: jobLevelId,
          },
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);
}
