// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp4H2IDB5PExZC8TlBQ5sMPbc8VliYFEk',
    appId: '1:1082310731253:web:9a0d2a9f2ae2ba0f1b2cbc',
    messagingSenderId: '1082310731253',
    projectId: 'alita-pricelist',
    authDomain: 'alita-pricelist.firebaseapp.com',
    storageBucket: 'alita-pricelist.firebasestorage.app',
    measurementId: 'G-YWCCZ7CKBE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB1jjr8iHJ3WZRSsk33EbQqc_pKr-sN54',
    appId: '1:1082310731253:android:2ab023b279888d7e1b2cbc',
    messagingSenderId: '1082310731253',
    projectId: 'alita-pricelist',
    storageBucket: 'alita-pricelist.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVI9sKlSJRd-RcQ3-JGgrLxj9iUBo0J28',
    appId: '1:1082310731253:ios:0ff3325f1841dc471b2cbc',
    messagingSenderId: '1082310731253',
    projectId: 'alita-pricelist',
    storageBucket: 'alita-pricelist.firebasestorage.app',
    iosBundleId: 'com.syahrul.app2.alitapricelist2',
  );
}
