// Mocks generated by Mockito 5.4.6 from annotations
// in alitapricelist/test/features/approval/domain/usecases/get_approvals_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:alitapricelist/features/approval/data/datasources/approval_local_data_source.dart'
    as _i3;
import 'package:alitapricelist/features/approval/data/datasources/approval_remote_data_source.dart'
    as _i2;
import 'package:alitapricelist/features/approval/data/repositories/approval_repository.dart'
    as _i4;
import 'package:alitapricelist/features/approval/domain/entities/approval_entity.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApprovalRemoteDataSource_0 extends _i1.SmartFake
    implements _i2.ApprovalRemoteDataSource {
  _FakeApprovalRemoteDataSource_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeApprovalLocalDataSource_1 extends _i1.SmartFake
    implements _i3.ApprovalLocalDataSource {
  _FakeApprovalLocalDataSource_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApprovalRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockApprovalRepository extends _i1.Mock
    implements _i4.ApprovalRepository {
  MockApprovalRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApprovalRemoteDataSource get remoteDataSource => (super.noSuchMethod(
        Invocation.getter(#remoteDataSource),
        returnValue: _FakeApprovalRemoteDataSource_0(
          this,
          Invocation.getter(#remoteDataSource),
        ),
      ) as _i2.ApprovalRemoteDataSource);

  @override
  _i3.ApprovalLocalDataSource get localDataSource => (super.noSuchMethod(
        Invocation.getter(#localDataSource),
        returnValue: _FakeApprovalLocalDataSource_1(
          this,
          Invocation.getter(#localDataSource),
        ),
      ) as _i3.ApprovalLocalDataSource);

  @override
  _i5.Future<List<_i6.ApprovalEntity>> getApprovals({
    String? creator,
    bool? forceRefresh = false,
    String? dateFrom,
    String? dateTo,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getApprovals,
          [],
          {
            #creator: creator,
            #forceRefresh: forceRefresh,
            #dateFrom: dateFrom,
            #dateTo: dateTo,
          },
        ),
        returnValue:
            _i5.Future<List<_i6.ApprovalEntity>>.value(<_i6.ApprovalEntity>[]),
      ) as _i5.Future<List<_i6.ApprovalEntity>>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getDiscountsForTimeline(
          int? orderLetterId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDiscountsForTimeline,
          [orderLetterId],
        ),
        returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<Map<String, dynamic>?> getCachedUserInfo() => (super.noSuchMethod(
        Invocation.method(
          #getCachedUserInfo,
          [],
        ),
        returnValue: _i5.Future<Map<String, dynamic>?>.value(),
      ) as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<void> cacheUserInfo(Map<String, dynamic>? userInfo) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheUserInfo,
          [userInfo],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i6.ApprovalEntity>> getApprovalsWithPagination({
    String? creator,
    bool? forceRefresh = false,
    int? page = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getApprovalsWithPagination,
          [],
          {
            #creator: creator,
            #forceRefresh: forceRefresh,
            #page: page,
          },
        ),
        returnValue:
            _i5.Future<List<_i6.ApprovalEntity>>.value(<_i6.ApprovalEntity>[]),
      ) as _i5.Future<List<_i6.ApprovalEntity>>);

  @override
  _i5.Future<Map<String, dynamic>> getPaginationInfo() => (super.noSuchMethod(
        Invocation.method(
          #getPaginationInfo,
          [],
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<void> backgroundSync() => (super.noSuchMethod(
        Invocation.method(
          #backgroundSync,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i6.ApprovalEntity>> getApprovalsFromCacheOnly() =>
      (super.noSuchMethod(
        Invocation.method(
          #getApprovalsFromCacheOnly,
          [],
        ),
        returnValue:
            _i5.Future<List<_i6.ApprovalEntity>>.value(<_i6.ApprovalEntity>[]),
      ) as _i5.Future<List<_i6.ApprovalEntity>>);

  @override
  _i5.Future<void> testCachePerformance() => (super.noSuchMethod(
        Invocation.method(
          #testCachePerformance,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i6.ApprovalEntity?> updateSingleApproval(int? orderLetterId) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSingleApproval,
          [orderLetterId],
        ),
        returnValue: _i5.Future<_i6.ApprovalEntity?>.value(),
      ) as _i5.Future<_i6.ApprovalEntity?>);

  @override
  _i5.Future<bool> refreshSingleApproval(int? orderLetterId) =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshSingleApproval,
          [orderLetterId],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<List<_i6.ApprovalEntity>> loadNewApprovalsIncremental() =>
      (super.noSuchMethod(
        Invocation.method(
          #loadNewApprovalsIncremental,
          [],
        ),
        returnValue:
            _i5.Future<List<_i6.ApprovalEntity>>.value(<_i6.ApprovalEntity>[]),
      ) as _i5.Future<List<_i6.ApprovalEntity>>);

  @override
  _i5.Future<List<_i6.ApprovalEntity>> updateApprovalStatusesOnly() =>
      (super.noSuchMethod(
        Invocation.method(
          #updateApprovalStatusesOnly,
          [],
        ),
        returnValue:
            _i5.Future<List<_i6.ApprovalEntity>>.value(<_i6.ApprovalEntity>[]),
      ) as _i5.Future<List<_i6.ApprovalEntity>>);

  @override
  _i5.Future<void> clearCache() => (super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i6.ApprovalEntity?> getApprovalById(int? orderLetterId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getApprovalById,
          [orderLetterId],
        ),
        returnValue: _i5.Future<_i6.ApprovalEntity?>.value(),
      ) as _i5.Future<_i6.ApprovalEntity?>);

  @override
  _i5.Future<Map<String, dynamic>> createApproval({
    required int? orderLetterId,
    required String? action,
    required String? approverName,
    required String? approverEmail,
    String? comment,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createApproval,
          [],
          {
            #orderLetterId: orderLetterId,
            #action: action,
            #approverName: approverName,
            #approverEmail: approverEmail,
            #comment: comment,
          },
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<List<_i6.ApprovalEntity>> getApprovalsByStatus(
    String? status, {
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getApprovalsByStatus,
          [status],
          {#forceRefresh: forceRefresh},
        ),
        returnValue:
            _i5.Future<List<_i6.ApprovalEntity>>.value(<_i6.ApprovalEntity>[]),
      ) as _i5.Future<List<_i6.ApprovalEntity>>);

  @override
  _i5.Future<List<_i6.ApprovalEntity>> getPendingApprovals(
          {bool? forceRefresh = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingApprovals,
          [],
          {#forceRefresh: forceRefresh},
        ),
        returnValue:
            _i5.Future<List<_i6.ApprovalEntity>>.value(<_i6.ApprovalEntity>[]),
      ) as _i5.Future<List<_i6.ApprovalEntity>>);

  @override
  _i5.Future<List<_i6.ApprovalEntity>> getApprovedApprovals(
          {bool? forceRefresh = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getApprovedApprovals,
          [],
          {#forceRefresh: forceRefresh},
        ),
        returnValue:
            _i5.Future<List<_i6.ApprovalEntity>>.value(<_i6.ApprovalEntity>[]),
      ) as _i5.Future<List<_i6.ApprovalEntity>>);

  @override
  _i5.Future<List<_i6.ApprovalEntity>> getRejectedApprovals(
          {bool? forceRefresh = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRejectedApprovals,
          [],
          {#forceRefresh: forceRefresh},
        ),
        returnValue:
            _i5.Future<List<_i6.ApprovalEntity>>.value(<_i6.ApprovalEntity>[]),
      ) as _i5.Future<List<_i6.ApprovalEntity>>);
}
