// Mocks generated by Mockito 5.4.6 from annotations
// in alitapricelist/test/widget/approval_monitoring_page_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:alitapricelist/features/approval/data/datasources/approval_local_data_source.dart'
    as _i4;
import 'package:alitapricelist/features/approval/data/datasources/approval_remote_data_source.dart'
    as _i3;
import 'package:alitapricelist/features/approval/data/repositories/approval_repository.dart'
    as _i2;
import 'package:alitapricelist/features/approval/domain/entities/approval_entity.dart'
    as _i8;
import 'package:alitapricelist/features/approval/domain/usecases/create_approval_usecase.dart'
    as _i9;
import 'package:alitapricelist/features/approval/domain/usecases/get_approvals_usecase.dart'
    as _i6;
import 'package:alitapricelist/services/order_letter_service.dart' as _i10;
import 'package:dio/dio.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApprovalRepository_0 extends _i1.SmartFake
    implements _i2.ApprovalRepository {
  _FakeApprovalRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeApprovalRemoteDataSource_1 extends _i1.SmartFake
    implements _i3.ApprovalRemoteDataSource {
  _FakeApprovalRemoteDataSource_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeApprovalLocalDataSource_2 extends _i1.SmartFake
    implements _i4.ApprovalLocalDataSource {
  _FakeApprovalLocalDataSource_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDio_3 extends _i1.SmartFake implements _i5.Dio {
  _FakeDio_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetApprovalsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetApprovalsUseCase extends _i1.Mock
    implements _i6.GetApprovalsUseCase {
  MockGetApprovalsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApprovalRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeApprovalRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ApprovalRepository);

  @override
  _i7.Future<List<_i8.ApprovalEntity>> call({
    String? creator,
    bool? forceRefresh = false,
    String? dateFrom,
    String? dateTo,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #creator: creator,
            #forceRefresh: forceRefresh,
            #dateFrom: dateFrom,
            #dateTo: dateTo,
          },
        ),
        returnValue:
            _i7.Future<List<_i8.ApprovalEntity>>.value(<_i8.ApprovalEntity>[]),
      ) as _i7.Future<List<_i8.ApprovalEntity>>);
}

/// A class which mocks [GetApprovalByIdUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetApprovalByIdUseCase extends _i1.Mock
    implements _i6.GetApprovalByIdUseCase {
  MockGetApprovalByIdUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApprovalRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeApprovalRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ApprovalRepository);

  @override
  _i7.Future<_i8.ApprovalEntity?> call(int? orderLetterId) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [orderLetterId],
        ),
        returnValue: _i7.Future<_i8.ApprovalEntity?>.value(),
      ) as _i7.Future<_i8.ApprovalEntity?>);
}

/// A class which mocks [GetPendingApprovalsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPendingApprovalsUseCase extends _i1.Mock
    implements _i6.GetPendingApprovalsUseCase {
  MockGetPendingApprovalsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApprovalRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeApprovalRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ApprovalRepository);

  @override
  _i7.Future<List<_i8.ApprovalEntity>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue:
            _i7.Future<List<_i8.ApprovalEntity>>.value(<_i8.ApprovalEntity>[]),
      ) as _i7.Future<List<_i8.ApprovalEntity>>);
}

/// A class which mocks [GetApprovedApprovalsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetApprovedApprovalsUseCase extends _i1.Mock
    implements _i6.GetApprovedApprovalsUseCase {
  MockGetApprovedApprovalsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApprovalRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeApprovalRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ApprovalRepository);

  @override
  _i7.Future<List<_i8.ApprovalEntity>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue:
            _i7.Future<List<_i8.ApprovalEntity>>.value(<_i8.ApprovalEntity>[]),
      ) as _i7.Future<List<_i8.ApprovalEntity>>);
}

/// A class which mocks [GetRejectedApprovalsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetRejectedApprovalsUseCase extends _i1.Mock
    implements _i6.GetRejectedApprovalsUseCase {
  MockGetRejectedApprovalsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApprovalRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeApprovalRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ApprovalRepository);

  @override
  _i7.Future<List<_i8.ApprovalEntity>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue:
            _i7.Future<List<_i8.ApprovalEntity>>.value(<_i8.ApprovalEntity>[]),
      ) as _i7.Future<List<_i8.ApprovalEntity>>);
}

/// A class which mocks [CreateApprovalUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateApprovalUseCase extends _i1.Mock
    implements _i9.CreateApprovalUseCase {
  MockCreateApprovalUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApprovalRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeApprovalRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ApprovalRepository);

  @override
  _i7.Future<Map<String, dynamic>> call({
    required int? orderLetterId,
    required String? action,
    required String? approverName,
    required String? approverEmail,
    String? comment,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #orderLetterId: orderLetterId,
            #action: action,
            #approverName: approverName,
            #approverEmail: approverEmail,
            #comment: comment,
          },
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);
}

/// A class which mocks [ApprovalRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockApprovalRepository extends _i1.Mock
    implements _i2.ApprovalRepository {
  MockApprovalRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.ApprovalRemoteDataSource get remoteDataSource => (super.noSuchMethod(
        Invocation.getter(#remoteDataSource),
        returnValue: _FakeApprovalRemoteDataSource_1(
          this,
          Invocation.getter(#remoteDataSource),
        ),
      ) as _i3.ApprovalRemoteDataSource);

  @override
  _i4.ApprovalLocalDataSource get localDataSource => (super.noSuchMethod(
        Invocation.getter(#localDataSource),
        returnValue: _FakeApprovalLocalDataSource_2(
          this,
          Invocation.getter(#localDataSource),
        ),
      ) as _i4.ApprovalLocalDataSource);

  @override
  _i7.Future<List<_i8.ApprovalEntity>> getApprovals({
    String? creator,
    bool? forceRefresh = false,
    String? dateFrom,
    String? dateTo,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getApprovals,
          [],
          {
            #creator: creator,
            #forceRefresh: forceRefresh,
            #dateFrom: dateFrom,
            #dateTo: dateTo,
          },
        ),
        returnValue:
            _i7.Future<List<_i8.ApprovalEntity>>.value(<_i8.ApprovalEntity>[]),
      ) as _i7.Future<List<_i8.ApprovalEntity>>);

  @override
  _i7.Future<List<Map<String, dynamic>>> getDiscountsForTimeline(
          int? orderLetterId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDiscountsForTimeline,
          [orderLetterId],
        ),
        returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i7.Future<List<Map<String, dynamic>>>);

  @override
  _i7.Future<Map<String, dynamic>?> getCachedUserInfo() => (super.noSuchMethod(
        Invocation.method(
          #getCachedUserInfo,
          [],
        ),
        returnValue: _i7.Future<Map<String, dynamic>?>.value(),
      ) as _i7.Future<Map<String, dynamic>?>);

  @override
  _i7.Future<void> cacheUserInfo(Map<String, dynamic>? userInfo) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheUserInfo,
          [userInfo],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i8.ApprovalEntity>> getApprovalsWithPagination({
    String? creator,
    bool? forceRefresh = false,
    int? page = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getApprovalsWithPagination,
          [],
          {
            #creator: creator,
            #forceRefresh: forceRefresh,
            #page: page,
          },
        ),
        returnValue:
            _i7.Future<List<_i8.ApprovalEntity>>.value(<_i8.ApprovalEntity>[]),
      ) as _i7.Future<List<_i8.ApprovalEntity>>);

  @override
  _i7.Future<Map<String, dynamic>> getPaginationInfo() => (super.noSuchMethod(
        Invocation.method(
          #getPaginationInfo,
          [],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<void> backgroundSync() => (super.noSuchMethod(
        Invocation.method(
          #backgroundSync,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i8.ApprovalEntity>> getApprovalsFromCacheOnly() =>
      (super.noSuchMethod(
        Invocation.method(
          #getApprovalsFromCacheOnly,
          [],
        ),
        returnValue:
            _i7.Future<List<_i8.ApprovalEntity>>.value(<_i8.ApprovalEntity>[]),
      ) as _i7.Future<List<_i8.ApprovalEntity>>);

  @override
  _i7.Future<void> testCachePerformance() => (super.noSuchMethod(
        Invocation.method(
          #testCachePerformance,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i8.ApprovalEntity?> updateSingleApproval(int? orderLetterId) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSingleApproval,
          [orderLetterId],
        ),
        returnValue: _i7.Future<_i8.ApprovalEntity?>.value(),
      ) as _i7.Future<_i8.ApprovalEntity?>);

  @override
  _i7.Future<bool> refreshSingleApproval(int? orderLetterId) =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshSingleApproval,
          [orderLetterId],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<List<_i8.ApprovalEntity>> loadNewApprovalsIncremental() =>
      (super.noSuchMethod(
        Invocation.method(
          #loadNewApprovalsIncremental,
          [],
        ),
        returnValue:
            _i7.Future<List<_i8.ApprovalEntity>>.value(<_i8.ApprovalEntity>[]),
      ) as _i7.Future<List<_i8.ApprovalEntity>>);

  @override
  _i7.Future<List<_i8.ApprovalEntity>> updateApprovalStatusesOnly() =>
      (super.noSuchMethod(
        Invocation.method(
          #updateApprovalStatusesOnly,
          [],
        ),
        returnValue:
            _i7.Future<List<_i8.ApprovalEntity>>.value(<_i8.ApprovalEntity>[]),
      ) as _i7.Future<List<_i8.ApprovalEntity>>);

  @override
  _i7.Future<void> clearCache() => (super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i8.ApprovalEntity?> getApprovalById(int? orderLetterId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getApprovalById,
          [orderLetterId],
        ),
        returnValue: _i7.Future<_i8.ApprovalEntity?>.value(),
      ) as _i7.Future<_i8.ApprovalEntity?>);

  @override
  _i7.Future<Map<String, dynamic>> createApproval({
    required int? orderLetterId,
    required String? action,
    required String? approverName,
    required String? approverEmail,
    String? comment,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createApproval,
          [],
          {
            #orderLetterId: orderLetterId,
            #action: action,
            #approverName: approverName,
            #approverEmail: approverEmail,
            #comment: comment,
          },
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<List<_i8.ApprovalEntity>> getApprovalsByStatus(
    String? status, {
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getApprovalsByStatus,
          [status],
          {#forceRefresh: forceRefresh},
        ),
        returnValue:
            _i7.Future<List<_i8.ApprovalEntity>>.value(<_i8.ApprovalEntity>[]),
      ) as _i7.Future<List<_i8.ApprovalEntity>>);

  @override
  _i7.Future<List<_i8.ApprovalEntity>> getPendingApprovals(
          {bool? forceRefresh = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingApprovals,
          [],
          {#forceRefresh: forceRefresh},
        ),
        returnValue:
            _i7.Future<List<_i8.ApprovalEntity>>.value(<_i8.ApprovalEntity>[]),
      ) as _i7.Future<List<_i8.ApprovalEntity>>);

  @override
  _i7.Future<List<_i8.ApprovalEntity>> getApprovedApprovals(
          {bool? forceRefresh = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getApprovedApprovals,
          [],
          {#forceRefresh: forceRefresh},
        ),
        returnValue:
            _i7.Future<List<_i8.ApprovalEntity>>.value(<_i8.ApprovalEntity>[]),
      ) as _i7.Future<List<_i8.ApprovalEntity>>);

  @override
  _i7.Future<List<_i8.ApprovalEntity>> getRejectedApprovals(
          {bool? forceRefresh = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRejectedApprovals,
          [],
          {#forceRefresh: forceRefresh},
        ),
        returnValue:
            _i7.Future<List<_i8.ApprovalEntity>>.value(<_i8.ApprovalEntity>[]),
      ) as _i7.Future<List<_i8.ApprovalEntity>>);
}

/// A class which mocks [OrderLetterService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderLetterService extends _i1.Mock
    implements _i10.OrderLetterService {
  MockOrderLetterService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_3(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i5.Dio);

  @override
  _i7.Future<Map<String, dynamic>> createOrderLetterWithDetails({
    required Map<String, dynamic>? orderLetterData,
    required List<Map<String, dynamic>>? detailsData,
    required dynamic discountsData,
    List<int?>? leaderIds,
    int? selectedSpvId,
    String? selectedSpvName,
    int? selectedRsmId,
    String? selectedRsmName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createOrderLetterWithDetails,
          [],
          {
            #orderLetterData: orderLetterData,
            #detailsData: detailsData,
            #discountsData: discountsData,
            #leaderIds: leaderIds,
            #selectedSpvId: selectedSpvId,
            #selectedSpvName: selectedSpvName,
            #selectedRsmId: selectedRsmId,
            #selectedRsmName: selectedRsmName,
          },
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>> createOrderLetter(
          Map<String, dynamic>? orderLetterData) =>
      (super.noSuchMethod(
        Invocation.method(
          #createOrderLetter,
          [orderLetterData],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>> createOrderLetterDetail(
          Map<String, dynamic>? detailData) =>
      (super.noSuchMethod(
        Invocation.method(
          #createOrderLetterDetail,
          [detailData],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>> createOrderLetterDiscount(
          Map<String, dynamic>? discountData) =>
      (super.noSuchMethod(
        Invocation.method(
          #createOrderLetterDiscount,
          [discountData],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>> batchApproveOrderLetterDiscounts({
    required int? orderLetterId,
    required int? leaderId,
    required int? jobLevelId,
    String? action = 'approve',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchApproveOrderLetterDiscounts,
          [],
          {
            #orderLetterId: orderLetterId,
            #leaderId: leaderId,
            #jobLevelId: jobLevelId,
            #action: action,
          },
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>> approveOrderLetterDiscount({
    required int? discountId,
    required int? leaderId,
    required int? jobLevelId,
    required int? orderLetterId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #approveOrderLetterDiscount,
          [],
          {
            #discountId: discountId,
            #leaderId: leaderId,
            #jobLevelId: jobLevelId,
            #orderLetterId: orderLetterId,
          },
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<List<Map<String, dynamic>>> getOrderLetters({
    String? creator,
    String? dateFrom,
    String? dateTo,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrderLetters,
          [],
          {
            #creator: creator,
            #dateFrom: dateFrom,
            #dateTo: dateTo,
          },
        ),
        returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i7.Future<List<Map<String, dynamic>>>);

  @override
  _i7.Future<List<Map<String, dynamic>>> getOrderLettersWithCompleteData({
    String? creator,
    bool? includeDetails = true,
    bool? includeDiscounts = true,
    bool? includeApprovals = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrderLettersWithCompleteData,
          [],
          {
            #creator: creator,
            #includeDetails: includeDetails,
            #includeDiscounts: includeDiscounts,
            #includeApprovals: includeApprovals,
          },
        ),
        returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i7.Future<List<Map<String, dynamic>>>);

  @override
  _i7.Future<List<Map<String, dynamic>>> getOrderLetterDetails(
          {int? orderLetterId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrderLetterDetails,
          [],
          {#orderLetterId: orderLetterId},
        ),
        returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i7.Future<List<Map<String, dynamic>>>);

  @override
  _i7.Future<List<Map<String, dynamic>>> getOrderLetterDiscounts(
          {int? orderLetterId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrderLetterDiscounts,
          [],
          {#orderLetterId: orderLetterId},
        ),
        returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i7.Future<List<Map<String, dynamic>>>);

  @override
  _i7.Future<List<Map<String, dynamic>>> getOrderLetterApproves({
    int? orderLetterId,
    String? approverId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrderLetterApproves,
          [],
          {
            #orderLetterId: orderLetterId,
            #approverId: approverId,
          },
        ),
        returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i7.Future<List<Map<String, dynamic>>>);

  @override
  _i7.Future<Map<String, dynamic>> createOrderLetterApprove(
          Map<String, dynamic>? approveData) =>
      (super.noSuchMethod(
        Invocation.method(
          #createOrderLetterApprove,
          [approveData],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<int> getPendingDiscountCount({
    required int? orderLetterId,
    required int? leaderId,
    required int? jobLevelId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingDiscountCount,
          [],
          {
            #orderLetterId: orderLetterId,
            #leaderId: leaderId,
            #jobLevelId: jobLevelId,
          },
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);
}
