// Mocks generated by Mockito 5.4.6 from annotations
// in alitapricelist/test/widget/product_page_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i13;

import 'package:alitapricelist/features/authentication/data/datasources/auth_local_data_source.dart'
    as _i6;
import 'package:alitapricelist/features/authentication/data/datasources/auth_remote_data_source.dart'
    as _i5;
import 'package:alitapricelist/features/authentication/data/models/auth_model.dart'
    as _i8;
import 'package:alitapricelist/features/authentication/data/repositories/auth_repository.dart'
    as _i3;
import 'package:alitapricelist/features/authentication/domain/entities/auth_entity.dart'
    as _i4;
import 'package:alitapricelist/features/authentication/domain/usecases/login_usecase.dart'
    as _i15;
import 'package:alitapricelist/features/cart/domain/entities/cart_entity.dart'
    as _i23;
import 'package:alitapricelist/features/cart/domain/repositories/cart_repository.dart'
    as _i22;
import 'package:alitapricelist/features/product/data/datasources/area_remote_data_source.dart'
    as _i9;
import 'package:alitapricelist/features/product/data/datasources/brand_remote_data_source.dart'
    as _i11;
import 'package:alitapricelist/features/product/data/datasources/channel_remote_data_source.dart'
    as _i10;
import 'package:alitapricelist/features/product/data/models/area_model.dart'
    as _i17;
import 'package:alitapricelist/features/product/data/models/brand_model.dart'
    as _i21;
import 'package:alitapricelist/features/product/data/models/channel_model.dart'
    as _i19;
import 'package:alitapricelist/features/product/data/repositories/area_repository.dart'
    as _i16;
import 'package:alitapricelist/features/product/data/repositories/brand_repository.dart'
    as _i20;
import 'package:alitapricelist/features/product/data/repositories/channel_repository.dart'
    as _i18;
import 'package:alitapricelist/features/product/data/repositories/product_repository.dart'
    as _i2;
import 'package:alitapricelist/features/product/domain/entities/product_entity.dart'
    as _i14;
import 'package:alitapricelist/features/product/domain/usecases/get_product_usecase.dart'
    as _i12;
import 'package:flutter/foundation.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProductRepository_0 extends _i1.SmartFake
    implements _i2.ProductRepository {
  _FakeProductRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthRepository_1 extends _i1.SmartFake
    implements _i3.AuthRepository {
  _FakeAuthRepository_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthEntity_2 extends _i1.SmartFake implements _i4.AuthEntity {
  _FakeAuthEntity_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthRemoteDataSource_3 extends _i1.SmartFake
    implements _i5.AuthRemoteDataSource {
  _FakeAuthRemoteDataSource_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthLocalDataSource_4 extends _i1.SmartFake
    implements _i6.AuthLocalDataSource {
  _FakeAuthLocalDataSource_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeValueNotifier_5<T> extends _i1.SmartFake
    implements _i7.ValueNotifier<T> {
  _FakeValueNotifier_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthModel_6 extends _i1.SmartFake implements _i8.AuthModel {
  _FakeAuthModel_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAreaRemoteDataSource_7 extends _i1.SmartFake
    implements _i9.AreaRemoteDataSource {
  _FakeAreaRemoteDataSource_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeChannelRemoteDataSource_8 extends _i1.SmartFake
    implements _i10.ChannelRemoteDataSource {
  _FakeChannelRemoteDataSource_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBrandRemoteDataSource_9 extends _i1.SmartFake
    implements _i11.BrandRemoteDataSource {
  _FakeBrandRemoteDataSource_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetProductUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProductUseCase extends _i1.Mock implements _i12.GetProductUseCase {
  MockGetProductUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ProductRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeProductRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ProductRepository);

  @override
  _i13.Future<List<_i14.ProductEntity>> callWithFilter({
    required String? area,
    required String? channel,
    required String? brand,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #callWithFilter,
          [],
          {
            #area: area,
            #channel: channel,
            #brand: brand,
          },
        ),
        returnValue:
            _i13.Future<List<_i14.ProductEntity>>.value(<_i14.ProductEntity>[]),
      ) as _i13.Future<List<_i14.ProductEntity>>);
}

/// A class which mocks [LoginUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginUseCase extends _i1.Mock implements _i15.LoginUseCase {
  MockLoginUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.AuthRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeAuthRepository_1(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.AuthRepository);

  @override
  _i13.Future<_i4.AuthEntity> call(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [
            email,
            password,
          ],
        ),
        returnValue: _i13.Future<_i4.AuthEntity>.value(_FakeAuthEntity_2(
          this,
          Invocation.method(
            #call,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i13.Future<_i4.AuthEntity>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.AuthRemoteDataSource get remoteDataSource => (super.noSuchMethod(
        Invocation.getter(#remoteDataSource),
        returnValue: _FakeAuthRemoteDataSource_3(
          this,
          Invocation.getter(#remoteDataSource),
        ),
      ) as _i5.AuthRemoteDataSource);

  @override
  _i6.AuthLocalDataSource get localDataSource => (super.noSuchMethod(
        Invocation.getter(#localDataSource),
        returnValue: _FakeAuthLocalDataSource_4(
          this,
          Invocation.getter(#localDataSource),
        ),
      ) as _i6.AuthLocalDataSource);

  @override
  _i7.ValueNotifier<bool> get authChangeNotifier => (super.noSuchMethod(
        Invocation.getter(#authChangeNotifier),
        returnValue: _FakeValueNotifier_5<bool>(
          this,
          Invocation.getter(#authChangeNotifier),
        ),
      ) as _i7.ValueNotifier<bool>);

  @override
  _i13.Future<_i8.AuthModel> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
        ),
        returnValue: _i13.Future<_i8.AuthModel>.value(_FakeAuthModel_6(
          this,
          Invocation.method(
            #login,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i13.Future<_i8.AuthModel>);

  @override
  _i13.Future<String?> refreshToken() => (super.noSuchMethod(
        Invocation.method(
          #refreshToken,
          [],
        ),
        returnValue: _i13.Future<String?>.value(),
      ) as _i13.Future<String?>);

  @override
  _i13.Future<bool> isLoggedIn() => (super.noSuchMethod(
        Invocation.method(
          #isLoggedIn,
          [],
        ),
        returnValue: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<int?> getCurrentUserId() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUserId,
          [],
        ),
        returnValue: _i13.Future<int?>.value(),
      ) as _i13.Future<int?>);

  @override
  _i13.Future<String?> getCurrentUserName() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUserName,
          [],
        ),
        returnValue: _i13.Future<String?>.value(),
      ) as _i13.Future<String?>);

  @override
  _i13.Future<int?> getCurrentUserAreaId() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUserAreaId,
          [],
        ),
        returnValue: _i13.Future<int?>.value(),
      ) as _i13.Future<int?>);

  @override
  _i13.Future<String?> getCurrentUserAreaName() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUserAreaName,
          [],
        ),
        returnValue: _i13.Future<String?>.value(),
      ) as _i13.Future<String?>);

  @override
  _i13.Future<String?> getToken() => (super.noSuchMethod(
        Invocation.method(
          #getToken,
          [],
        ),
        returnValue: _i13.Future<String?>.value(),
      ) as _i13.Future<String?>);

  @override
  _i13.Future<String?> getRefreshToken() => (super.noSuchMethod(
        Invocation.method(
          #getRefreshToken,
          [],
        ),
        returnValue: _i13.Future<String?>.value(),
      ) as _i13.Future<String?>);

  @override
  _i13.Future<bool> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<void> saveEmail(String? email) => (super.noSuchMethod(
        Invocation.method(
          #saveEmail,
          [email],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<String?> getSavedEmail() => (super.noSuchMethod(
        Invocation.method(
          #getSavedEmail,
          [],
        ),
        returnValue: _i13.Future<String?>.value(),
      ) as _i13.Future<String?>);

  @override
  _i13.Future<void> clearSavedEmail() => (super.noSuchMethod(
        Invocation.method(
          #clearSavedEmail,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<bool> saveLoginData({
    required String? token,
    required String? refreshToken,
    required int? userId,
    required String? userName,
    int? areaId,
    String? areaName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveLoginData,
          [],
          {
            #token: token,
            #refreshToken: refreshToken,
            #userId: userId,
            #userName: userName,
            #areaId: areaId,
            #areaName: areaName,
          },
        ),
        returnValue: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);
}

/// A class which mocks [AreaRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAreaRepository extends _i1.Mock implements _i16.AreaRepository {
  MockAreaRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.AreaRemoteDataSource get remoteDataSource => (super.noSuchMethod(
        Invocation.getter(#remoteDataSource),
        returnValue: _FakeAreaRemoteDataSource_7(
          this,
          Invocation.getter(#remoteDataSource),
        ),
      ) as _i9.AreaRemoteDataSource);

  @override
  _i13.Future<List<_i17.AreaModel>> fetchAreas() => (super.noSuchMethod(
        Invocation.method(
          #fetchAreas,
          [],
        ),
        returnValue:
            _i13.Future<List<_i17.AreaModel>>.value(<_i17.AreaModel>[]),
      ) as _i13.Future<List<_i17.AreaModel>>);

  @override
  _i13.Future<_i17.AreaModel?> getAreaById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getAreaById,
          [id],
        ),
        returnValue: _i13.Future<_i17.AreaModel?>.value(),
      ) as _i13.Future<_i17.AreaModel?>);

  @override
  _i13.Future<_i17.AreaModel?> getAreaByName(String? name) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAreaByName,
          [name],
        ),
        returnValue: _i13.Future<_i17.AreaModel?>.value(),
      ) as _i13.Future<_i17.AreaModel?>);

  @override
  _i13.Future<List<String>> fetchAllAreaNames() => (super.noSuchMethod(
        Invocation.method(
          #fetchAllAreaNames,
          [],
        ),
        returnValue: _i13.Future<List<String>>.value(<String>[]),
      ) as _i13.Future<List<String>>);

  @override
  _i13.Future<bool> isApiAvailable() => (super.noSuchMethod(
        Invocation.method(
          #isApiAvailable,
          [],
        ),
        returnValue: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);
}

/// A class which mocks [ChannelRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChannelRepository extends _i1.Mock implements _i18.ChannelRepository {
  MockChannelRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.ChannelRemoteDataSource get remoteDataSource => (super.noSuchMethod(
        Invocation.getter(#remoteDataSource),
        returnValue: _FakeChannelRemoteDataSource_8(
          this,
          Invocation.getter(#remoteDataSource),
        ),
      ) as _i10.ChannelRemoteDataSource);

  @override
  _i13.Future<List<_i19.ChannelModel>> fetchChannels() => (super.noSuchMethod(
        Invocation.method(
          #fetchChannels,
          [],
        ),
        returnValue:
            _i13.Future<List<_i19.ChannelModel>>.value(<_i19.ChannelModel>[]),
      ) as _i13.Future<List<_i19.ChannelModel>>);

  @override
  _i13.Future<_i19.ChannelModel?> getChannelById(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChannelById,
          [id],
        ),
        returnValue: _i13.Future<_i19.ChannelModel?>.value(),
      ) as _i13.Future<_i19.ChannelModel?>);

  @override
  _i13.Future<_i19.ChannelModel?> getChannelByName(String? name) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChannelByName,
          [name],
        ),
        returnValue: _i13.Future<_i19.ChannelModel?>.value(),
      ) as _i13.Future<_i19.ChannelModel?>);

  @override
  _i13.Future<bool> isApiAvailable() => (super.noSuchMethod(
        Invocation.method(
          #isApiAvailable,
          [],
        ),
        returnValue: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<List<String>> fetchAllChannelNames() => (super.noSuchMethod(
        Invocation.method(
          #fetchAllChannelNames,
          [],
        ),
        returnValue: _i13.Future<List<String>>.value(<String>[]),
      ) as _i13.Future<List<String>>);

  @override
  _i13.Future<List<_i19.ChannelModel>> fetchAllChannels() =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchAllChannels,
          [],
        ),
        returnValue:
            _i13.Future<List<_i19.ChannelModel>>.value(<_i19.ChannelModel>[]),
      ) as _i13.Future<List<_i19.ChannelModel>>);
}

/// A class which mocks [BrandRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBrandRepository extends _i1.Mock implements _i20.BrandRepository {
  MockBrandRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.BrandRemoteDataSource get remoteDataSource => (super.noSuchMethod(
        Invocation.getter(#remoteDataSource),
        returnValue: _FakeBrandRemoteDataSource_9(
          this,
          Invocation.getter(#remoteDataSource),
        ),
      ) as _i11.BrandRemoteDataSource);

  @override
  _i13.Future<List<_i21.BrandModel>> fetchBrands() => (super.noSuchMethod(
        Invocation.method(
          #fetchBrands,
          [],
        ),
        returnValue:
            _i13.Future<List<_i21.BrandModel>>.value(<_i21.BrandModel>[]),
      ) as _i13.Future<List<_i21.BrandModel>>);

  @override
  _i13.Future<_i21.BrandModel?> getBrandById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getBrandById,
          [id],
        ),
        returnValue: _i13.Future<_i21.BrandModel?>.value(),
      ) as _i13.Future<_i21.BrandModel?>);

  @override
  _i13.Future<_i21.BrandModel?> getBrandByName(String? name) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBrandByName,
          [name],
        ),
        returnValue: _i13.Future<_i21.BrandModel?>.value(),
      ) as _i13.Future<_i21.BrandModel?>);

  @override
  _i13.Future<bool> isApiAvailable() => (super.noSuchMethod(
        Invocation.method(
          #isApiAvailable,
          [],
        ),
        returnValue: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<List<String>> fetchAllBrandNames({int? channelId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchAllBrandNames,
          [],
          {#channelId: channelId},
        ),
        returnValue: _i13.Future<List<String>>.value(<String>[]),
      ) as _i13.Future<List<String>>);

  @override
  _i13.Future<List<_i21.BrandModel>> fetchAllBrands({int? channelId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchAllBrands,
          [],
          {#channelId: channelId},
        ),
        returnValue:
            _i13.Future<List<_i21.BrandModel>>.value(<_i21.BrandModel>[]),
      ) as _i13.Future<List<_i21.BrandModel>>);
}

/// A class which mocks [CartRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCartRepository extends _i1.Mock implements _i22.CartRepository {
  MockCartRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<List<_i23.CartEntity>> loadCartItems() => (super.noSuchMethod(
        Invocation.method(
          #loadCartItems,
          [],
        ),
        returnValue:
            _i13.Future<List<_i23.CartEntity>>.value(<_i23.CartEntity>[]),
      ) as _i13.Future<List<_i23.CartEntity>>);

  @override
  _i13.Future<bool> saveCartItems(List<_i23.CartEntity>? cartItems) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveCartItems,
          [cartItems],
        ),
        returnValue: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<bool> clearCart() => (super.noSuchMethod(
        Invocation.method(
          #clearCart,
          [],
        ),
        returnValue: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);
}
