// Mocks generated by Mockito 5.4.6 from annotations
// in alitapricelist/test/helpers/test_setup.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:alitapricelist/features/product/data/datasources/area_remote_data_source.dart'
    as _i2;
import 'package:alitapricelist/features/product/data/datasources/brand_remote_data_source.dart'
    as _i4;
import 'package:alitapricelist/features/product/data/datasources/channel_remote_data_source.dart'
    as _i3;
import 'package:alitapricelist/features/product/data/models/area_model.dart'
    as _i8;
import 'package:alitapricelist/features/product/data/models/brand_model.dart'
    as _i12;
import 'package:alitapricelist/features/product/data/models/channel_model.dart'
    as _i10;
import 'package:alitapricelist/features/product/data/repositories/area_repository.dart'
    as _i6;
import 'package:alitapricelist/features/product/data/repositories/brand_repository.dart'
    as _i11;
import 'package:alitapricelist/features/product/data/repositories/channel_repository.dart'
    as _i9;
import 'package:alitapricelist/features/product/data/repositories/product_repository.dart'
    as _i5;
import 'package:alitapricelist/features/product/domain/entities/product_entity.dart'
    as _i14;
import 'package:alitapricelist/features/product/domain/usecases/get_product_usecase.dart'
    as _i13;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAreaRemoteDataSource_0 extends _i1.SmartFake
    implements _i2.AreaRemoteDataSource {
  _FakeAreaRemoteDataSource_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeChannelRemoteDataSource_1 extends _i1.SmartFake
    implements _i3.ChannelRemoteDataSource {
  _FakeChannelRemoteDataSource_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBrandRemoteDataSource_2 extends _i1.SmartFake
    implements _i4.BrandRemoteDataSource {
  _FakeBrandRemoteDataSource_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProductRepository_3 extends _i1.SmartFake
    implements _i5.ProductRepository {
  _FakeProductRepository_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AreaRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAreaRepository extends _i1.Mock implements _i6.AreaRepository {
  MockAreaRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AreaRemoteDataSource get remoteDataSource => (super.noSuchMethod(
        Invocation.getter(#remoteDataSource),
        returnValue: _FakeAreaRemoteDataSource_0(
          this,
          Invocation.getter(#remoteDataSource),
        ),
      ) as _i2.AreaRemoteDataSource);

  @override
  _i7.Future<List<_i8.AreaModel>> fetchAreas() => (super.noSuchMethod(
        Invocation.method(
          #fetchAreas,
          [],
        ),
        returnValue: _i7.Future<List<_i8.AreaModel>>.value(<_i8.AreaModel>[]),
      ) as _i7.Future<List<_i8.AreaModel>>);

  @override
  _i7.Future<_i8.AreaModel?> getAreaById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getAreaById,
          [id],
        ),
        returnValue: _i7.Future<_i8.AreaModel?>.value(),
      ) as _i7.Future<_i8.AreaModel?>);

  @override
  _i7.Future<_i8.AreaModel?> getAreaByName(String? name) => (super.noSuchMethod(
        Invocation.method(
          #getAreaByName,
          [name],
        ),
        returnValue: _i7.Future<_i8.AreaModel?>.value(),
      ) as _i7.Future<_i8.AreaModel?>);

  @override
  _i7.Future<List<String>> fetchAllAreaNames() => (super.noSuchMethod(
        Invocation.method(
          #fetchAllAreaNames,
          [],
        ),
        returnValue: _i7.Future<List<String>>.value(<String>[]),
      ) as _i7.Future<List<String>>);

  @override
  _i7.Future<bool> isApiAvailable() => (super.noSuchMethod(
        Invocation.method(
          #isApiAvailable,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);
}

/// A class which mocks [ChannelRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChannelRepository extends _i1.Mock implements _i9.ChannelRepository {
  MockChannelRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.ChannelRemoteDataSource get remoteDataSource => (super.noSuchMethod(
        Invocation.getter(#remoteDataSource),
        returnValue: _FakeChannelRemoteDataSource_1(
          this,
          Invocation.getter(#remoteDataSource),
        ),
      ) as _i3.ChannelRemoteDataSource);

  @override
  _i7.Future<List<_i10.ChannelModel>> fetchChannels() => (super.noSuchMethod(
        Invocation.method(
          #fetchChannels,
          [],
        ),
        returnValue:
            _i7.Future<List<_i10.ChannelModel>>.value(<_i10.ChannelModel>[]),
      ) as _i7.Future<List<_i10.ChannelModel>>);

  @override
  _i7.Future<_i10.ChannelModel?> getChannelById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getChannelById,
          [id],
        ),
        returnValue: _i7.Future<_i10.ChannelModel?>.value(),
      ) as _i7.Future<_i10.ChannelModel?>);

  @override
  _i7.Future<_i10.ChannelModel?> getChannelByName(String? name) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChannelByName,
          [name],
        ),
        returnValue: _i7.Future<_i10.ChannelModel?>.value(),
      ) as _i7.Future<_i10.ChannelModel?>);

  @override
  _i7.Future<bool> isApiAvailable() => (super.noSuchMethod(
        Invocation.method(
          #isApiAvailable,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<List<String>> fetchAllChannelNames() => (super.noSuchMethod(
        Invocation.method(
          #fetchAllChannelNames,
          [],
        ),
        returnValue: _i7.Future<List<String>>.value(<String>[]),
      ) as _i7.Future<List<String>>);

  @override
  _i7.Future<List<_i10.ChannelModel>> fetchAllChannels() => (super.noSuchMethod(
        Invocation.method(
          #fetchAllChannels,
          [],
        ),
        returnValue:
            _i7.Future<List<_i10.ChannelModel>>.value(<_i10.ChannelModel>[]),
      ) as _i7.Future<List<_i10.ChannelModel>>);
}

/// A class which mocks [BrandRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBrandRepository extends _i1.Mock implements _i11.BrandRepository {
  MockBrandRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.BrandRemoteDataSource get remoteDataSource => (super.noSuchMethod(
        Invocation.getter(#remoteDataSource),
        returnValue: _FakeBrandRemoteDataSource_2(
          this,
          Invocation.getter(#remoteDataSource),
        ),
      ) as _i4.BrandRemoteDataSource);

  @override
  _i7.Future<List<_i12.BrandModel>> fetchBrands() => (super.noSuchMethod(
        Invocation.method(
          #fetchBrands,
          [],
        ),
        returnValue:
            _i7.Future<List<_i12.BrandModel>>.value(<_i12.BrandModel>[]),
      ) as _i7.Future<List<_i12.BrandModel>>);

  @override
  _i7.Future<_i12.BrandModel?> getBrandById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getBrandById,
          [id],
        ),
        returnValue: _i7.Future<_i12.BrandModel?>.value(),
      ) as _i7.Future<_i12.BrandModel?>);

  @override
  _i7.Future<_i12.BrandModel?> getBrandByName(String? name) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBrandByName,
          [name],
        ),
        returnValue: _i7.Future<_i12.BrandModel?>.value(),
      ) as _i7.Future<_i12.BrandModel?>);

  @override
  _i7.Future<bool> isApiAvailable() => (super.noSuchMethod(
        Invocation.method(
          #isApiAvailable,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<List<String>> fetchAllBrandNames({int? channelId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchAllBrandNames,
          [],
          {#channelId: channelId},
        ),
        returnValue: _i7.Future<List<String>>.value(<String>[]),
      ) as _i7.Future<List<String>>);

  @override
  _i7.Future<List<_i12.BrandModel>> fetchAllBrands({int? channelId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchAllBrands,
          [],
          {#channelId: channelId},
        ),
        returnValue:
            _i7.Future<List<_i12.BrandModel>>.value(<_i12.BrandModel>[]),
      ) as _i7.Future<List<_i12.BrandModel>>);
}

/// A class which mocks [GetProductUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProductUseCase extends _i1.Mock implements _i13.GetProductUseCase {
  MockGetProductUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.ProductRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeProductRepository_3(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i5.ProductRepository);

  @override
  _i7.Future<List<_i14.ProductEntity>> callWithFilter({
    required String? area,
    required String? channel,
    required String? brand,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #callWithFilter,
          [],
          {
            #area: area,
            #channel: channel,
            #brand: brand,
          },
        ),
        returnValue:
            _i7.Future<List<_i14.ProductEntity>>.value(<_i14.ProductEntity>[]),
      ) as _i7.Future<List<_i14.ProductEntity>>);
}
