// Mocks generated by Mockito 5.4.6 from annotations
// in alitapricelist/test/features/product/domain/usecases/get_item_lookup_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:alitapricelist/features/product/domain/entities/item_lookup_entity.dart'
    as _i4;
import 'package:alitapricelist/features/product/domain/repositories/item_lookup_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ItemLookupRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockItemLookupRepository extends _i1.Mock
    implements _i2.ItemLookupRepository {
  MockItemLookupRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.ItemLookupEntity>> fetchItemLookups() =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchItemLookups,
          [],
        ),
        returnValue: _i3.Future<List<_i4.ItemLookupEntity>>.value(
            <_i4.ItemLookupEntity>[]),
      ) as _i3.Future<List<_i4.ItemLookupEntity>>);

  @override
  _i3.Future<List<_i4.ItemLookupEntity>> fetchLookupItems({
    required String? brand,
    required String? kasur,
    String? divan,
    String? headboard,
    String? sorong,
    required String? ukuran,
    String? contextItemType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchLookupItems,
          [],
          {
            #brand: brand,
            #kasur: kasur,
            #divan: divan,
            #headboard: headboard,
            #sorong: sorong,
            #ukuran: ukuran,
            #contextItemType: contextItemType,
          },
        ),
        returnValue: _i3.Future<List<_i4.ItemLookupEntity>>.value(
            <_i4.ItemLookupEntity>[]),
      ) as _i3.Future<List<_i4.ItemLookupEntity>>);
}
