// Mocks generated by Mockito 5.4.6 from annotations
// in alitapricelist/test/integration/auth_bloc_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:alitapricelist/features/authentication/data/datasources/auth_local_data_source.dart'
    as _i5;
import 'package:alitapricelist/features/authentication/data/datasources/auth_remote_data_source.dart'
    as _i4;
import 'package:alitapricelist/features/authentication/data/models/auth_model.dart'
    as _i7;
import 'package:alitapricelist/features/authentication/data/repositories/auth_repository.dart'
    as _i2;
import 'package:alitapricelist/features/authentication/domain/entities/auth_entity.dart'
    as _i3;
import 'package:alitapricelist/features/authentication/domain/usecases/login_usecase.dart'
    as _i8;
import 'package:flutter/foundation.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthRepository_0 extends _i1.SmartFake
    implements _i2.AuthRepository {
  _FakeAuthRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthEntity_1 extends _i1.SmartFake implements _i3.AuthEntity {
  _FakeAuthEntity_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthRemoteDataSource_2 extends _i1.SmartFake
    implements _i4.AuthRemoteDataSource {
  _FakeAuthRemoteDataSource_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthLocalDataSource_3 extends _i1.SmartFake
    implements _i5.AuthLocalDataSource {
  _FakeAuthLocalDataSource_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeValueNotifier_4<T> extends _i1.SmartFake
    implements _i6.ValueNotifier<T> {
  _FakeValueNotifier_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthModel_5 extends _i1.SmartFake implements _i7.AuthModel {
  _FakeAuthModel_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LoginUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginUseCase extends _i1.Mock implements _i8.LoginUseCase {
  MockLoginUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeAuthRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.AuthRepository);

  @override
  _i9.Future<_i3.AuthEntity> call(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [
            email,
            password,
          ],
        ),
        returnValue: _i9.Future<_i3.AuthEntity>.value(_FakeAuthEntity_1(
          this,
          Invocation.method(
            #call,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i9.Future<_i3.AuthEntity>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i2.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.AuthRemoteDataSource get remoteDataSource => (super.noSuchMethod(
        Invocation.getter(#remoteDataSource),
        returnValue: _FakeAuthRemoteDataSource_2(
          this,
          Invocation.getter(#remoteDataSource),
        ),
      ) as _i4.AuthRemoteDataSource);

  @override
  _i5.AuthLocalDataSource get localDataSource => (super.noSuchMethod(
        Invocation.getter(#localDataSource),
        returnValue: _FakeAuthLocalDataSource_3(
          this,
          Invocation.getter(#localDataSource),
        ),
      ) as _i5.AuthLocalDataSource);

  @override
  _i6.ValueNotifier<bool> get authChangeNotifier => (super.noSuchMethod(
        Invocation.getter(#authChangeNotifier),
        returnValue: _FakeValueNotifier_4<bool>(
          this,
          Invocation.getter(#authChangeNotifier),
        ),
      ) as _i6.ValueNotifier<bool>);

  @override
  _i9.Future<_i7.AuthModel> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
        ),
        returnValue: _i9.Future<_i7.AuthModel>.value(_FakeAuthModel_5(
          this,
          Invocation.method(
            #login,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i9.Future<_i7.AuthModel>);

  @override
  _i9.Future<String?> refreshToken() => (super.noSuchMethod(
        Invocation.method(
          #refreshToken,
          [],
        ),
        returnValue: _i9.Future<String?>.value(),
      ) as _i9.Future<String?>);

  @override
  _i9.Future<bool> isLoggedIn() => (super.noSuchMethod(
        Invocation.method(
          #isLoggedIn,
          [],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<int?> getCurrentUserId() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUserId,
          [],
        ),
        returnValue: _i9.Future<int?>.value(),
      ) as _i9.Future<int?>);

  @override
  _i9.Future<String?> getCurrentUserName() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUserName,
          [],
        ),
        returnValue: _i9.Future<String?>.value(),
      ) as _i9.Future<String?>);

  @override
  _i9.Future<int?> getCurrentUserAreaId() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUserAreaId,
          [],
        ),
        returnValue: _i9.Future<int?>.value(),
      ) as _i9.Future<int?>);

  @override
  _i9.Future<String?> getCurrentUserAreaName() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUserAreaName,
          [],
        ),
        returnValue: _i9.Future<String?>.value(),
      ) as _i9.Future<String?>);

  @override
  _i9.Future<String?> getToken() => (super.noSuchMethod(
        Invocation.method(
          #getToken,
          [],
        ),
        returnValue: _i9.Future<String?>.value(),
      ) as _i9.Future<String?>);

  @override
  _i9.Future<String?> getRefreshToken() => (super.noSuchMethod(
        Invocation.method(
          #getRefreshToken,
          [],
        ),
        returnValue: _i9.Future<String?>.value(),
      ) as _i9.Future<String?>);

  @override
  _i9.Future<bool> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<void> saveEmail(String? email) => (super.noSuchMethod(
        Invocation.method(
          #saveEmail,
          [email],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<String?> getSavedEmail() => (super.noSuchMethod(
        Invocation.method(
          #getSavedEmail,
          [],
        ),
        returnValue: _i9.Future<String?>.value(),
      ) as _i9.Future<String?>);

  @override
  _i9.Future<void> clearSavedEmail() => (super.noSuchMethod(
        Invocation.method(
          #clearSavedEmail,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<bool> saveLoginData({
    required String? token,
    required String? refreshToken,
    required int? userId,
    required String? userName,
    int? areaId,
    String? areaName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveLoginData,
          [],
          {
            #token: token,
            #refreshToken: refreshToken,
            #userId: userId,
            #userName: userName,
            #areaId: areaId,
            #areaName: areaName,
          },
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);
}
